services:
  app:
    build: .
    ports:
      - 8080:${NODE_PORT:-8080}
    environment:
      MONGO_URI: mongodb://db/db
  db:
    image: mongo
    #env:
    #  MONGO_INITDB_DATABASE = "your-application"